Creating delete_links for issue #79 provide delete_link function
davidban77/gns3fy pull request #91
Opened 2020-11-03 21:52 UTC by Krlosromero

PR for fixing Issue #79. 
function `delete_links` created and tests passed successfully.

2020-11-03 22:37 UTC, davidban77 requested changes
Seems to be pretty good!

For some reason the tests didn't trigger automatically and I might have to check on that later, but can you run them and paste them here?

2020-11-03 23:14 UTC, Krlosromero commented
below the tests output

```
# carlosromero @ Carloss-MacBook-Pro in ~/workspace/gns3fy on git:master o [23:12:05] C:1
$ pytest  -v tests/test_gns3fy.py
============================================ test session starts =============================================
platform darwin -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0 -- /Users/carlosromero/anaconda3/envs/gns3fy/bin/python
cachedir: .pytest_cache
rootdir: /Users/carlosromero/workspace/gns3fy
plugins: requests-mock-1.7.0, cov-2.7.1
collected 136 items                                                                                          

tests/test_gns3fy.py::TestGns3Connector::test_get_version PASSED                                       [  0%]
tests/test_gns3fy.py::TestGns3Connector::test_get_templates PASSED                                     [  1%]
tests/test_gns3fy.py::TestGns3Connector::test_get_template_by_name PASSED                              [  2%]
tests/test_gns3fy.py::TestGns3Connector::test_get_template_by_id PASSED                                [  2%]
tests/test_gns3fy.py::TestGns3Connector::test_error_get_template_no_params PASSED                      [  3%]
tests/test_gns3fy.py::TestGns3Connector::test_error_template_id_not_found PASSED                       [  4%]
tests/test_gns3fy.py::TestGns3Connector::test_error_template_name_not_found PASSED                     [  5%]
tests/test_gns3fy.py::TestGns3Connector::test_create_template PASSED                                   [  5%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_template_already_used PASSED                [  6%]
tests/test_gns3fy.py::TestGns3Connector::test_update_template PASSED                                   [  7%]
tests/test_gns3fy.py::TestGns3Connector::test_delete_template PASSED                                   [  8%]
tests/test_gns3fy.py::TestGns3Connector::test_get_projects PASSED                                      [  8%]
tests/test_gns3fy.py::TestGns3Connector::test_get_project_by_name PASSED                               [  9%]
tests/test_gns3fy.py::TestGns3Connector::test_get_project_by_id PASSED                                 [ 10%]
tests/test_gns3fy.py::TestGns3Connector::test_error_get_project_no_params PASSED                       [ 11%]
tests/test_gns3fy.py::TestGns3Connector::test_error_project_id_not_found PASSED                        [ 11%]
tests/test_gns3fy.py::TestGns3Connector::test_error_project_name_not_found PASSED                      [ 12%]
tests/test_gns3fy.py::TestGns3Connector::test_get_nodes PASSED                                         [ 13%]
tests/test_gns3fy.py::TestGns3Connector::test_get_node_by_id PASSED                                    [ 13%]
tests/test_gns3fy.py::TestGns3Connector::test_error_node_not_found PASSED                              [ 14%]
tests/test_gns3fy.py::TestGns3Connector::test_get_links PASSED                                         [ 15%]
tests/test_gns3fy.py::TestGns3Connector::test_get_link_by_id PASSED                                    [ 16%]
tests/test_gns3fy.py::TestGns3Connector::test_error_link_not_found PASSED                              [ 16%]
tests/test_gns3fy.py::TestGns3Connector::test_create_project PASSED                                    [ 17%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_duplicate_project PASSED                    [ 18%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_project_with_no_name PASSED                 [ 19%]
tests/test_gns3fy.py::TestGns3Connector::test_delete_project PASSED                                    [ 19%]
tests/test_gns3fy.py::TestGns3Connector::test_projects_summary PASSED                                  [ 20%]
tests/test_gns3fy.py::TestGns3Connector::test_projects_summary_print PASSED                            [ 21%]
tests/test_gns3fy.py::TestGns3Connector::test_templates_summary PASSED                                 [ 22%]
tests/test_gns3fy.py::TestGns3Connector::test_templates_summary_print PASSED                           [ 22%]
tests/test_gns3fy.py::TestGns3Connector::test_get_computes PASSED                                      [ 23%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute PASSED                                       [ 24%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute_qemu_images PASSED                           [ 25%]
tests/test_gns3fy.py::TestGns3Connector::test_upload_compute_image_not_found PASSED                    [ 25%]
tests/test_gns3fy.py::TestGns3Connector::test_upload_compute_image PASSED                              [ 26%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute_ports PASSED                                 [ 27%]
tests/test_gns3fy.py::TestGns3Connector::test_wrong_server_url FAILED                                  [ 27%]
tests/test_gns3fy.py::TestLink::test_instatiation PASSED                                               [ 28%]
tests/test_gns3fy.py::TestLink::test_error_instatiation_bad_link_type PASSED                           [ 29%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 30%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params1-Need to submit project_id] PASSED [ 30%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params2-Need to submit link_id] PASSED [ 31%]
tests/test_gns3fy.py::TestLink::test_get PASSED                                                        [ 32%]
tests/test_gns3fy.py::TestLink::test_error_create_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 33%]
tests/test_gns3fy.py::TestLink::test_error_create_with_no_required_param[params1-Need to submit project_id] PASSED [ 33%]
tests/test_gns3fy.py::TestLink::test_create PASSED                                                     [ 34%]
tests/test_gns3fy.py::TestLink::test_error_create_with_incomplete_node_data PASSED                     [ 35%]
tests/test_gns3fy.py::TestLink::test_error_create_connecting_to_itself PASSED                          [ 36%]
tests/test_gns3fy.py::TestLink::test_delete PASSED                                                     [ 36%]
tests/test_gns3fy.py::TestNode::test_instatiation PASSED                                               [ 37%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param0-Not a valid node_type - dummy] PASSED [ 38%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param1-Not a valid console_type - dummy] PASSED [ 38%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param2-Not a valid status - dummy] PASSED [ 39%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 40%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params1-Need to submit project_id] PASSED [ 41%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params2-Need to either submit node_id or name] PASSED [ 41%]
tests/test_gns3fy.py::TestNode::test_get PASSED                                                        [ 42%]
tests/test_gns3fy.py::TestNode::test_get_links PASSED                                                  [ 43%]
tests/test_gns3fy.py::TestNode::test_start PASSED                                                      [ 44%]
tests/test_gns3fy.py::TestNode::test_stop PASSED                                                       [ 44%]
tests/test_gns3fy.py::TestNode::test_suspend PASSED                                                    [ 45%]
tests/test_gns3fy.py::TestNode::test_reload PASSED                                                     [ 46%]
tests/test_gns3fy.py::TestNode::test_create[param0] PASSED                                             [ 47%]
tests/test_gns3fy.py::TestNode::test_create[param1] PASSED                                             [ 47%]
tests/test_gns3fy.py::TestNode::test_create_override_pro [...]

2020-11-03 23:54 UTC, Krlosromero commented
After updating Poetry... ALL tests PASSED 👍 

```
$ pytest  -v tests/test_gns3fy.py
============================================ test session starts =============================================
platform darwin -- Python 3.9.0, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /Users/carlosromero/anaconda3/envs/gns3fy/bin/python
cachedir: .pytest_cache
rootdir: /Users/carlosromero/workspace/gns3fy
plugins: requests-mock-1.8.0, cov-2.8.1
collected 136 items                                                                                          

tests/test_gns3fy.py::TestGns3Connector::test_get_version PASSED                                       [  0%]
tests/test_gns3fy.py::TestGns3Connector::test_get_templates PASSED                                     [  1%]
tests/test_gns3fy.py::TestGns3Connector::test_get_template_by_name PASSED                              [  2%]
tests/test_gns3fy.py::TestGns3Connector::test_get_template_by_id PASSED                                [  2%]
tests/test_gns3fy.py::TestGns3Connector::test_error_get_template_no_params PASSED                      [  3%]
tests/test_gns3fy.py::TestGns3Connector::test_error_template_id_not_found PASSED                       [  4%]
tests/test_gns3fy.py::TestGns3Connector::test_error_template_name_not_found PASSED                     [  5%]
tests/test_gns3fy.py::TestGns3Connector::test_create_template PASSED                                   [  5%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_template_already_used PASSED                [  6%]
tests/test_gns3fy.py::TestGns3Connector::test_update_template PASSED                                   [  7%]
tests/test_gns3fy.py::TestGns3Connector::test_delete_template PASSED                                   [  8%]
tests/test_gns3fy.py::TestGns3Connector::test_get_projects PASSED                                      [  8%]
tests/test_gns3fy.py::TestGns3Connector::test_get_project_by_name PASSED                               [  9%]
tests/test_gns3fy.py::TestGns3Connector::test_get_project_by_id PASSED                                 [ 10%]
tests/test_gns3fy.py::TestGns3Connector::test_error_get_project_no_params PASSED                       [ 11%]
tests/test_gns3fy.py::TestGns3Connector::test_error_project_id_not_found PASSED                        [ 11%]
tests/test_gns3fy.py::TestGns3Connector::test_error_project_name_not_found PASSED                      [ 12%]
tests/test_gns3fy.py::TestGns3Connector::test_get_nodes PASSED                                         [ 13%]
tests/test_gns3fy.py::TestGns3Connector::test_get_node_by_id PASSED                                    [ 13%]
tests/test_gns3fy.py::TestGns3Connector::test_error_node_not_found PASSED                              [ 14%]
tests/test_gns3fy.py::TestGns3Connector::test_get_links PASSED                                         [ 15%]
tests/test_gns3fy.py::TestGns3Connector::test_get_link_by_id PASSED                                    [ 16%]
tests/test_gns3fy.py::TestGns3Connector::test_error_link_not_found PASSED                              [ 16%]
tests/test_gns3fy.py::TestGns3Connector::test_create_project PASSED                                    [ 17%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_duplicate_project PASSED                    [ 18%]
tests/test_gns3fy.py::TestGns3Connector::test_error_create_project_with_no_name PASSED                 [ 19%]
tests/test_gns3fy.py::TestGns3Connector::test_delete_project PASSED                                    [ 19%]
tests/test_gns3fy.py::TestGns3Connector::test_projects_summary PASSED                                  [ 20%]
tests/test_gns3fy.py::TestGns3Connector::test_projects_summary_print PASSED                            [ 21%]
tests/test_gns3fy.py::TestGns3Connector::test_templates_summary PASSED                                 [ 22%]
tests/test_gns3fy.py::TestGns3Connector::test_templates_summary_print PASSED                           [ 22%]
tests/test_gns3fy.py::TestGns3Connector::test_get_computes PASSED                                      [ 23%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute PASSED                                       [ 24%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute_qemu_images PASSED                           [ 25%]
tests/test_gns3fy.py::TestGns3Connector::test_upload_compute_image_not_found PASSED                    [ 25%]
tests/test_gns3fy.py::TestGns3Connector::test_upload_compute_image PASSED                              [ 26%]
tests/test_gns3fy.py::TestGns3Connector::test_get_compute_ports PASSED                                 [ 27%]
tests/test_gns3fy.py::TestGns3Connector::test_wrong_server_url PASSED                                  [ 27%]
tests/test_gns3fy.py::TestLink::test_instatiation PASSED                                               [ 28%]
tests/test_gns3fy.py::TestLink::test_error_instatiation_bad_link_type PASSED                           [ 29%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 30%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params1-Need to submit project_id] PASSED [ 30%]
tests/test_gns3fy.py::TestLink::test_error_get_with_no_required_param[params2-Need to submit link_id] PASSED [ 31%]
tests/test_gns3fy.py::TestLink::test_get PASSED                                                        [ 32%]
tests/test_gns3fy.py::TestLink::test_error_create_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 33%]
tests/test_gns3fy.py::TestLink::test_error_create_with_no_required_param[params1-Need to submit project_id] PASSED [ 33%]
tests/test_gns3fy.py::TestLink::test_create PASSED                                                     [ 34%]
tests/test_gns3fy.py::TestLink::test_error_create_with_incomplete_node_data PASSED                     [ 35%]
tests/test_gns3fy.py::TestLink::test_error_create_connecting_to_itself PASSED                          [ 36%]
tests/test_gns3fy.py::TestLink::test_delete PASSED                                                     [ 36%]
tests/test_gns3fy.py::TestNode::test_instatiation PASSED                                               [ 37%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param0-Not a valid node_type - dummy] PASSED [ 38%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param1-Not a valid console_type - dummy] PASSED [ 38%]
tests/test_gns3fy.py::TestNode::test_error_link_instatiation_bad_param[param2-Not a valid status - dummy] PASSED [ 39%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params0-Gns3Connector not assigned under 'connector'] PASSED [ 40%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params1-Need to submit project_id] PASSED [ 41%]
tests/test_gns3fy.py::TestNode::test_error_get_with_no_required_param[params2-Need to either submit node_id or name] PASSED [ 41%]
tests/test_gns3fy.py::TestNode::test_get PASSED                                                        [ 42%]
tests/test_gns3fy.py::TestNode::test_get_links PASSED                                                  [ 43%]
tests/test_gns3fy.py::TestNode::test_start PASSED                                                      [ 44%]
tests/test_gns3fy.py::TestNode::test_stop PASSED                                                       [ 44%]
tests/test_gns3fy.py::TestNode::test_suspend PASSED                                                    [ 45%]
tests/test_gns3fy.py::TestNode::test_reload PASSED                                                     [ 46%]
tests/test_gns3fy.py::TestNode::test_create[param0] PASSED                                             [ 47%]
tests/test_gns3fy.py::TestNode::test_create[param1] PASSED                                             [ 47%]
tests/test_gns3fy.py::TestNode::test_create_override_properties PASSED                                 [ 48%]
tests/test_gns [...]

2020-11-04 06:42 UTC, merged

2020-11-04 06:42 UTC, davidban77 reviewed
LGTM